server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elearning?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Trithuc23@
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
app:
  jwt:
    secret: ${JWT_SECRET:change-this-very-long-secret-string-1234567890} # >= 32 bytes
    expirySeconds: 86400